env:
    browser: true
    commonjs: true
    es2021: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:vue/vue3-essential
parserOptions:
    ecmaVersion: latest
    parser: "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint"
    - vue
rules:
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - windows
    quotes:
        - error
        - double
    semi:
        - error
        - always
